// generated by: generate_version_info.sh "1.2.0" "y.nasretdinov@corp.badoo.com" "" "/Applications/Xcode.app/Contents/Developer/usr/bin/make - " 
// DO NOT EDIT!

package main

import (
	"badoo/_packages/service"
	"badoo/_packages/service/stats"
	"github.com/gogo/protobuf/proto"
)

func init() {
	service.VersionInfo = badoo_service.ResponseVersion{
		Version:        proto.String("1.2.0"),
		Maintainer:     proto.String("y.nasretdinov@corp.badoo.com"),
		AutoBuildTag:   proto.String(""),
		BuildDate:      proto.String("Tue Aug 30 13:58:14 UTC 2016"),
		BuildHost:      proto.String("nasretdinov.local"),
		BuildGoVersion: proto.String("go version go1.7 darwin/amd64"),
		BuildCommand:   proto.String("/Applications/Xcode.app/Contents/Developer/usr/bin/make - "),
		VcsType:        proto.String("git"),
		VcsBasename:    proto.String("thunder"),
		VcsNum:         proto.String("51"),
		VcsDate:        proto.String("2016-06-22T10:03:37+0000"),
		VcsBranch:      proto.String("CT-2552_kill_right_from_init"),
		VcsTag:         proto.String(""),
		VcsTick:        proto.String("51"),
		VcsFullHash:    proto.String("9e79ceebe05bd5d64a7af2b547a55dc55f0dc449"),
		VcsShortHash:   proto.String("9e79cee"),
		VcsWcModified:  proto.String("1"),
	}
}
