// Code generated by protoc-gen-gogo.
// source: thunder-config.proto
// DO NOT EDIT!

/*
Package thunder is a generated protocol buffer package.

It is generated from these files:
	thunder-config.proto

It has these top-level messages:
	ConfigT
*/
package thunder

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ConfigT struct {
	Mysql                         *ConfigTMysqlT    `protobuf:"bytes,1,req,name=mysql" json:"mysql,omitempty"`
	ExitWithParent                *bool             `protobuf:"varint,2,opt,name=exit_with_parent,def=0" json:"exit_with_parent,omitempty"`
	Delay                         *uint32           `protobuf:"varint,3,opt,name=delay,def=0" json:"delay,omitempty"`
	Default                       *ConfigTDefaultT  `protobuf:"bytes,4,req,name=default" json:"default,omitempty"`
	CycleMs                       *int64            `protobuf:"varint,5,opt,name=cycle_ms,def=1000" json:"cycle_ms,omitempty"`
	FullTimetableReloadIntervalMs *int64            `protobuf:"varint,6,opt,name=full_timetable_reload_interval_ms,def=1000" json:"full_timetable_reload_interval_ms,omitempty"`
	Launcher                      *ConfigTLauncherT `protobuf:"bytes,7,req,name=launcher" json:"launcher,omitempty"`
	IsDevel                       *bool             `protobuf:"varint,8,req,name=is_devel" json:"is_devel,omitempty"`
	XXX_unrecognized              []byte            `json:"-"`
}

func (m *ConfigT) Reset()         { *m = ConfigT{} }
func (m *ConfigT) String() string { return proto.CompactTextString(m) }
func (*ConfigT) ProtoMessage()    {}

const Default_ConfigT_ExitWithParent bool = false
const Default_ConfigT_Delay uint32 = 0
const Default_ConfigT_CycleMs int64 = 1000
const Default_ConfigT_FullTimetableReloadIntervalMs int64 = 1000

func (m *ConfigT) GetMysql() *ConfigTMysqlT {
	if m != nil {
		return m.Mysql
	}
	return nil
}

func (m *ConfigT) GetExitWithParent() bool {
	if m != nil && m.ExitWithParent != nil {
		return *m.ExitWithParent
	}
	return Default_ConfigT_ExitWithParent
}

func (m *ConfigT) GetDelay() uint32 {
	if m != nil && m.Delay != nil {
		return *m.Delay
	}
	return Default_ConfigT_Delay
}

func (m *ConfigT) GetDefault() *ConfigTDefaultT {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *ConfigT) GetCycleMs() int64 {
	if m != nil && m.CycleMs != nil {
		return *m.CycleMs
	}
	return Default_ConfigT_CycleMs
}

func (m *ConfigT) GetFullTimetableReloadIntervalMs() int64 {
	if m != nil && m.FullTimetableReloadIntervalMs != nil {
		return *m.FullTimetableReloadIntervalMs
	}
	return Default_ConfigT_FullTimetableReloadIntervalMs
}

func (m *ConfigT) GetLauncher() *ConfigTLauncherT {
	if m != nil {
		return m.Launcher
	}
	return nil
}

func (m *ConfigT) GetIsDevel() bool {
	if m != nil && m.IsDevel != nil {
		return *m.IsDevel
	}
	return false
}

type ConfigTMysqlT struct {
	Dsn              *string `protobuf:"bytes,1,req,name=dsn" json:"dsn,omitempty"`
	MaxConnections   *uint32 `protobuf:"varint,2,req,name=max_connections" json:"max_connections,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ConfigTMysqlT) Reset()         { *m = ConfigTMysqlT{} }
func (m *ConfigTMysqlT) String() string { return proto.CompactTextString(m) }
func (*ConfigTMysqlT) ProtoMessage()    {}

func (m *ConfigTMysqlT) GetDsn() string {
	if m != nil && m.Dsn != nil {
		return *m.Dsn
	}
	return ""
}

func (m *ConfigTMysqlT) GetMaxConnections() uint32 {
	if m != nil && m.MaxConnections != nil {
		return *m.MaxConnections
	}
	return 0
}

type ConfigTDefaultT struct {
	// average parasite memory on devel and production servers if we were to guess
	ParasiteMemory *int64 `protobuf:"varint,1,opt,name=parasite_memory,def=838860800" json:"parasite_memory,omitempty"`
	// minimum requirements for hosts to be considered alive
	MinMemory      *int64   `protobuf:"varint,2,opt,name=min_memory,def=1073741824" json:"min_memory,omitempty"`
	MinMemoryRatio *float64 `protobuf:"fixed64,3,opt,name=min_memory_ratio,def=0.01" json:"min_memory_ratio,omitempty"`
	MinIdleCpu     *float64 `protobuf:"fixed64,4,opt,name=min_idle_cpu,def=-0.15" json:"min_idle_cpu,omitempty"`
	// average script memory usage in bytes
	MaxMemory        *int64   `protobuf:"varint,5,opt,name=max_memory,def=52428800" json:"max_memory,omitempty"`
	Rusage           *float64 `protobuf:"fixed64,6,opt,name=rusage,def=0.02" json:"rusage,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ConfigTDefaultT) Reset()         { *m = ConfigTDefaultT{} }
func (m *ConfigTDefaultT) String() string { return proto.CompactTextString(m) }
func (*ConfigTDefaultT) ProtoMessage()    {}

const Default_ConfigTDefaultT_ParasiteMemory int64 = 838860800
const Default_ConfigTDefaultT_MinMemory int64 = 1073741824
const Default_ConfigTDefaultT_MinMemoryRatio float64 = 0.01
const Default_ConfigTDefaultT_MinIdleCpu float64 = -0.15
const Default_ConfigTDefaultT_MaxMemory int64 = 52428800
const Default_ConfigTDefaultT_Rusage float64 = 0.02

func (m *ConfigTDefaultT) GetParasiteMemory() int64 {
	if m != nil && m.ParasiteMemory != nil {
		return *m.ParasiteMemory
	}
	return Default_ConfigTDefaultT_ParasiteMemory
}

func (m *ConfigTDefaultT) GetMinMemory() int64 {
	if m != nil && m.MinMemory != nil {
		return *m.MinMemory
	}
	return Default_ConfigTDefaultT_MinMemory
}

func (m *ConfigTDefaultT) GetMinMemoryRatio() float64 {
	if m != nil && m.MinMemoryRatio != nil {
		return *m.MinMemoryRatio
	}
	return Default_ConfigTDefaultT_MinMemoryRatio
}

func (m *ConfigTDefaultT) GetMinIdleCpu() float64 {
	if m != nil && m.MinIdleCpu != nil {
		return *m.MinIdleCpu
	}
	return Default_ConfigTDefaultT_MinIdleCpu
}

func (m *ConfigTDefaultT) GetMaxMemory() int64 {
	if m != nil && m.MaxMemory != nil {
		return *m.MaxMemory
	}
	return Default_ConfigTDefaultT_MaxMemory
}

func (m *ConfigTDefaultT) GetRusage() float64 {
	if m != nil && m.Rusage != nil {
		return *m.Rusage
	}
	return Default_ConfigTDefaultT_Rusage
}

type ConfigTLauncherT struct {
	HostSuffix       *string `protobuf:"bytes,1,req,name=host_suffix" json:"host_suffix,omitempty"`
	BaseDir          *string `protobuf:"bytes,2,req,name=base_dir" json:"base_dir,omitempty"`
	DeveloperDir     *string `protobuf:"bytes,3,opt,name=developer_dir" json:"developer_dir,omitempty"`
	RqhLogFile       *string `protobuf:"bytes,4,req,name=rqh_log_file" json:"rqh_log_file,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ConfigTLauncherT) Reset()         { *m = ConfigTLauncherT{} }
func (m *ConfigTLauncherT) String() string { return proto.CompactTextString(m) }
func (*ConfigTLauncherT) ProtoMessage()    {}

func (m *ConfigTLauncherT) GetHostSuffix() string {
	if m != nil && m.HostSuffix != nil {
		return *m.HostSuffix
	}
	return ""
}

func (m *ConfigTLauncherT) GetBaseDir() string {
	if m != nil && m.BaseDir != nil {
		return *m.BaseDir
	}
	return ""
}

func (m *ConfigTLauncherT) GetDeveloperDir() string {
	if m != nil && m.DeveloperDir != nil {
		return *m.DeveloperDir
	}
	return ""
}

func (m *ConfigTLauncherT) GetRqhLogFile() string {
	if m != nil && m.RqhLogFile != nil {
		return *m.RqhLogFile
	}
	return ""
}
