// Code generated by protoc-gen-gogo.
// source: thunder.proto
// DO NOT EDIT!

/*
Package thunder is a generated protocol buffer package.

It is generated from these files:
	thunder.proto

It has these top-level messages:
	ResponseGeneric
	RequestHeartbeat
	RequestPhproxydHeartbeat
	RequestAddJobs
	ResponseJobIds
	RequestUpdateStatus
	RequestLogFinish
	ResponseRunInfo
*/
package thunder

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RequestMsgid int32

const (
	RequestMsgid_REQUEST_ADD_JOBS      RequestMsgid = 1
	RequestMsgid_REQUEST_UPDATE_STATUS RequestMsgid = 2
	RequestMsgid_REQUEST_LOG_FINISH    RequestMsgid = 3
)

var RequestMsgid_name = map[int32]string{
	1: "REQUEST_ADD_JOBS",
	2: "REQUEST_UPDATE_STATUS",
	3: "REQUEST_LOG_FINISH",
}
var RequestMsgid_value = map[string]int32{
	"REQUEST_ADD_JOBS":      1,
	"REQUEST_UPDATE_STATUS": 2,
	"REQUEST_LOG_FINISH":    3,
}

func (x RequestMsgid) Enum() *RequestMsgid {
	p := new(RequestMsgid)
	*p = x
	return p
}
func (x RequestMsgid) String() string {
	return proto.EnumName(RequestMsgid_name, int32(x))
}
func (x *RequestMsgid) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestMsgid_value, data, "RequestMsgid")
	if err != nil {
		return err
	}
	*x = RequestMsgid(value)
	return nil
}

type ResponseMsgid int32

const (
	ResponseMsgid_RESPONSE_GENERIC  ResponseMsgid = 1
	ResponseMsgid_RESPONSE_JOB_IDS  ResponseMsgid = 2
	ResponseMsgid_RESPONSE_RUN_INFO ResponseMsgid = 3
)

var ResponseMsgid_name = map[int32]string{
	1: "RESPONSE_GENERIC",
	2: "RESPONSE_JOB_IDS",
	3: "RESPONSE_RUN_INFO",
}
var ResponseMsgid_value = map[string]int32{
	"RESPONSE_GENERIC":  1,
	"RESPONSE_JOB_IDS":  2,
	"RESPONSE_RUN_INFO": 3,
}

func (x ResponseMsgid) Enum() *ResponseMsgid {
	p := new(ResponseMsgid)
	*p = x
	return p
}
func (x ResponseMsgid) String() string {
	return proto.EnumName(ResponseMsgid_name, int32(x))
}
func (x *ResponseMsgid) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResponseMsgid_value, data, "ResponseMsgid")
	if err != nil {
		return err
	}
	*x = ResponseMsgid(value)
	return nil
}

type Errno int32

const (
	Errno_ERRNO_GENERIC Errno = 1
)

var Errno_name = map[int32]string{
	1: "ERRNO_GENERIC",
}
var Errno_value = map[string]int32{
	"ERRNO_GENERIC": 1,
}

func (x Errno) Enum() *Errno {
	p := new(Errno)
	*p = x
	return p
}
func (x Errno) String() string {
	return proto.EnumName(Errno_name, int32(x))
}
func (x *Errno) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Errno_value, data, "Errno")
	if err != nil {
		return err
	}
	*x = Errno(value)
	return nil
}

type ResponseGeneric struct {
	ErrorCode        *int32  `protobuf:"zigzag32,1,req,name=error_code" json:"error_code,omitempty"`
	ErrorText        *string `protobuf:"bytes,2,opt,name=error_text" json:"error_text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponseGeneric) Reset()         { *m = ResponseGeneric{} }
func (m *ResponseGeneric) String() string { return proto.CompactTextString(m) }
func (*ResponseGeneric) ProtoMessage()    {}

func (m *ResponseGeneric) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *ResponseGeneric) GetErrorText() string {
	if m != nil && m.ErrorText != nil {
		return *m.ErrorText
	}
	return ""
}

type RequestHeartbeat struct {
	Hostname          *string                  `protobuf:"bytes,1,req,name=hostname" json:"hostname,omitempty"`
	Hostgroup         *string                  `protobuf:"bytes,2,req,name=hostgroup" json:"hostgroup,omitempty"`
	CpuParrotsPerCore *uint32                  `protobuf:"varint,3,opt,name=cpu_parrots_per_core" json:"cpu_parrots_per_core,omitempty"`
	CpuCores          *uint32                  `protobuf:"varint,4,req,name=cpu_cores" json:"cpu_cores,omitempty"`
	Cpu               *RequestHeartbeatCpuT    `protobuf:"bytes,5,opt,name=cpu" json:"cpu,omitempty"`
	Memory            *RequestHeartbeatMemoryT `protobuf:"bytes,6,opt,name=memory" json:"memory,omitempty"`
	XXX_unrecognized  []byte                   `json:"-"`
}

func (m *RequestHeartbeat) Reset()         { *m = RequestHeartbeat{} }
func (m *RequestHeartbeat) String() string { return proto.CompactTextString(m) }
func (*RequestHeartbeat) ProtoMessage()    {}

func (m *RequestHeartbeat) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *RequestHeartbeat) GetHostgroup() string {
	if m != nil && m.Hostgroup != nil {
		return *m.Hostgroup
	}
	return ""
}

func (m *RequestHeartbeat) GetCpuParrotsPerCore() uint32 {
	if m != nil && m.CpuParrotsPerCore != nil {
		return *m.CpuParrotsPerCore
	}
	return 0
}

func (m *RequestHeartbeat) GetCpuCores() uint32 {
	if m != nil && m.CpuCores != nil {
		return *m.CpuCores
	}
	return 0
}

func (m *RequestHeartbeat) GetCpu() *RequestHeartbeatCpuT {
	if m != nil {
		return m.Cpu
	}
	return nil
}

func (m *RequestHeartbeat) GetMemory() *RequestHeartbeatMemoryT {
	if m != nil {
		return m.Memory
	}
	return nil
}

type RequestHeartbeatCpuT struct {
	User             *float32 `protobuf:"fixed32,1,req,name=user" json:"user,omitempty"`
	Sys              *float32 `protobuf:"fixed32,2,req,name=sys" json:"sys,omitempty"`
	Nice             *float32 `protobuf:"fixed32,3,req,name=nice" json:"nice,omitempty"`
	Iowait           *float32 `protobuf:"fixed32,4,req,name=iowait" json:"iowait,omitempty"`
	Steal            *float32 `protobuf:"fixed32,5,req,name=steal" json:"steal,omitempty"`
	Idle             *float32 `protobuf:"fixed32,6,req,name=idle" json:"idle,omitempty"`
	Parasite         *float32 `protobuf:"fixed32,7,req,name=parasite" json:"parasite,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RequestHeartbeatCpuT) Reset()         { *m = RequestHeartbeatCpuT{} }
func (m *RequestHeartbeatCpuT) String() string { return proto.CompactTextString(m) }
func (*RequestHeartbeatCpuT) ProtoMessage()    {}

func (m *RequestHeartbeatCpuT) GetUser() float32 {
	if m != nil && m.User != nil {
		return *m.User
	}
	return 0
}

func (m *RequestHeartbeatCpuT) GetSys() float32 {
	if m != nil && m.Sys != nil {
		return *m.Sys
	}
	return 0
}

func (m *RequestHeartbeatCpuT) GetNice() float32 {
	if m != nil && m.Nice != nil {
		return *m.Nice
	}
	return 0
}

func (m *RequestHeartbeatCpuT) GetIowait() float32 {
	if m != nil && m.Iowait != nil {
		return *m.Iowait
	}
	return 0
}

func (m *RequestHeartbeatCpuT) GetSteal() float32 {
	if m != nil && m.Steal != nil {
		return *m.Steal
	}
	return 0
}

func (m *RequestHeartbeatCpuT) GetIdle() float32 {
	if m != nil && m.Idle != nil {
		return *m.Idle
	}
	return 0
}

func (m *RequestHeartbeatCpuT) GetParasite() float32 {
	if m != nil && m.Parasite != nil {
		return *m.Parasite
	}
	return 0
}

type RequestHeartbeatMemoryT struct {
	Total            *int64 `protobuf:"varint,1,req,name=total" json:"total,omitempty"`
	Free             *int64 `protobuf:"varint,2,req,name=free" json:"free,omitempty"`
	Cached           *int64 `protobuf:"varint,3,req,name=cached" json:"cached,omitempty"`
	Buffers          *int64 `protobuf:"varint,4,req,name=buffers" json:"buffers,omitempty"`
	Parasite         *int64 `protobuf:"varint,5,req,name=parasite" json:"parasite,omitempty"`
	SwapTotal        *int64 `protobuf:"varint,6,req,name=swap_total" json:"swap_total,omitempty"`
	SwapUsed         *int64 `protobuf:"varint,7,req,name=swap_used" json:"swap_used,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RequestHeartbeatMemoryT) Reset()         { *m = RequestHeartbeatMemoryT{} }
func (m *RequestHeartbeatMemoryT) String() string { return proto.CompactTextString(m) }
func (*RequestHeartbeatMemoryT) ProtoMessage()    {}

func (m *RequestHeartbeatMemoryT) GetTotal() int64 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *RequestHeartbeatMemoryT) GetFree() int64 {
	if m != nil && m.Free != nil {
		return *m.Free
	}
	return 0
}

func (m *RequestHeartbeatMemoryT) GetCached() int64 {
	if m != nil && m.Cached != nil {
		return *m.Cached
	}
	return 0
}

func (m *RequestHeartbeatMemoryT) GetBuffers() int64 {
	if m != nil && m.Buffers != nil {
		return *m.Buffers
	}
	return 0
}

func (m *RequestHeartbeatMemoryT) GetParasite() int64 {
	if m != nil && m.Parasite != nil {
		return *m.Parasite
	}
	return 0
}

func (m *RequestHeartbeatMemoryT) GetSwapTotal() int64 {
	if m != nil && m.SwapTotal != nil {
		return *m.SwapTotal
	}
	return 0
}

func (m *RequestHeartbeatMemoryT) GetSwapUsed() int64 {
	if m != nil && m.SwapUsed != nil {
		return *m.SwapUsed
	}
	return 0
}

type RequestPhproxydHeartbeat struct {
	Hostname         *string `protobuf:"bytes,1,req,name=hostname" json:"hostname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestPhproxydHeartbeat) Reset()         { *m = RequestPhproxydHeartbeat{} }
func (m *RequestPhproxydHeartbeat) String() string { return proto.CompactTextString(m) }
func (*RequestPhproxydHeartbeat) ProtoMessage()    {}

func (m *RequestPhproxydHeartbeat) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

type RequestAddJobs struct {
	Jobs             []*RequestAddJobsJobT `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *RequestAddJobs) Reset()         { *m = RequestAddJobs{} }
func (m *RequestAddJobs) String() string { return proto.CompactTextString(m) }
func (*RequestAddJobs) ProtoMessage()    {}

func (m *RequestAddJobs) GetJobs() []*RequestAddJobsJobT {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type RequestAddJobsJobT struct {
	GenerationId     *int64                     `protobuf:"varint,1,opt,name=generation_id" json:"generation_id,omitempty"`
	ClassName        *string                    `protobuf:"bytes,2,req,name=class_name" json:"class_name,omitempty"`
	JobData          *string                    `protobuf:"bytes,3,req,name=job_data" json:"job_data,omitempty"`
	Method           *string                    `protobuf:"bytes,4,opt,name=method" json:"method,omitempty"`
	Location         *string                    `protobuf:"bytes,5,opt,name=location" json:"location,omitempty"`
	NextLaunchTs     *int64                     `protobuf:"varint,6,opt,name=next_launch_ts" json:"next_launch_ts,omitempty"`
	Repeat           *RequestAddJobsJobTRepeatT `protobuf:"bytes,7,opt,name=repeat" json:"repeat,omitempty"`
	SettingsId       *uint64                    `protobuf:"varint,8,opt,name=settings_id" json:"settings_id,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *RequestAddJobsJobT) Reset()         { *m = RequestAddJobsJobT{} }
func (m *RequestAddJobsJobT) String() string { return proto.CompactTextString(m) }
func (*RequestAddJobsJobT) ProtoMessage()    {}

func (m *RequestAddJobsJobT) GetGenerationId() int64 {
	if m != nil && m.GenerationId != nil {
		return *m.GenerationId
	}
	return 0
}

func (m *RequestAddJobsJobT) GetClassName() string {
	if m != nil && m.ClassName != nil {
		return *m.ClassName
	}
	return ""
}

func (m *RequestAddJobsJobT) GetJobData() string {
	if m != nil && m.JobData != nil {
		return *m.JobData
	}
	return ""
}

func (m *RequestAddJobsJobT) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *RequestAddJobsJobT) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *RequestAddJobsJobT) GetNextLaunchTs() int64 {
	if m != nil && m.NextLaunchTs != nil {
		return *m.NextLaunchTs
	}
	return 0
}

func (m *RequestAddJobsJobT) GetRepeat() *RequestAddJobsJobTRepeatT {
	if m != nil {
		return m.Repeat
	}
	return nil
}

func (m *RequestAddJobsJobT) GetSettingsId() uint64 {
	if m != nil && m.SettingsId != nil {
		return *m.SettingsId
	}
	return 0
}

type RequestAddJobsJobTRepeatT struct {
	Value            *int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RequestAddJobsJobTRepeatT) Reset()         { *m = RequestAddJobsJobTRepeatT{} }
func (m *RequestAddJobsJobTRepeatT) String() string { return proto.CompactTextString(m) }
func (*RequestAddJobsJobTRepeatT) ProtoMessage()    {}

func (m *RequestAddJobsJobTRepeatT) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type ResponseJobIds struct {
	JobId            []uint64 `protobuf:"varint,1,rep,name=job_id" json:"job_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ResponseJobIds) Reset()         { *m = ResponseJobIds{} }
func (m *ResponseJobIds) String() string { return proto.CompactTextString(m) }
func (*ResponseJobIds) ProtoMessage()    {}

func (m *ResponseJobIds) GetJobId() []uint64 {
	if m != nil {
		return m.JobId
	}
	return nil
}

type RequestUpdateStatus struct {
	Hostname         *string `protobuf:"bytes,1,req,name=hostname" json:"hostname,omitempty"`
	RunId            *uint64 `protobuf:"varint,2,req,name=run_id" json:"run_id,omitempty"`
	PrevStatus       *string `protobuf:"bytes,3,req,name=prev_status" json:"prev_status,omitempty"`
	Status           *string `protobuf:"bytes,4,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestUpdateStatus) Reset()         { *m = RequestUpdateStatus{} }
func (m *RequestUpdateStatus) String() string { return proto.CompactTextString(m) }
func (*RequestUpdateStatus) ProtoMessage()    {}

func (m *RequestUpdateStatus) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *RequestUpdateStatus) GetRunId() uint64 {
	if m != nil && m.RunId != nil {
		return *m.RunId
	}
	return 0
}

func (m *RequestUpdateStatus) GetPrevStatus() string {
	if m != nil && m.PrevStatus != nil {
		return *m.PrevStatus
	}
	return ""
}

func (m *RequestUpdateStatus) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

type RequestLogFinish struct {
	Hostname         *string `protobuf:"bytes,1,req,name=hostname" json:"hostname,omitempty"`
	RunId            *uint64 `protobuf:"varint,2,req,name=run_id" json:"run_id,omitempty"`
	PrevStatus       *string `protobuf:"bytes,3,req,name=prev_status" json:"prev_status,omitempty"`
	Success          *bool   `protobuf:"varint,4,req,name=success" json:"success,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestLogFinish) Reset()         { *m = RequestLogFinish{} }
func (m *RequestLogFinish) String() string { return proto.CompactTextString(m) }
func (*RequestLogFinish) ProtoMessage()    {}

func (m *RequestLogFinish) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *RequestLogFinish) GetRunId() uint64 {
	if m != nil && m.RunId != nil {
		return *m.RunId
	}
	return 0
}

func (m *RequestLogFinish) GetPrevStatus() string {
	if m != nil && m.PrevStatus != nil {
		return *m.PrevStatus
	}
	return ""
}

func (m *RequestLogFinish) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

type ResponseRunInfo struct {
	Info             *string `protobuf:"bytes,1,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponseRunInfo) Reset()         { *m = ResponseRunInfo{} }
func (m *ResponseRunInfo) String() string { return proto.CompactTextString(m) }
func (*ResponseRunInfo) ProtoMessage()    {}

func (m *ResponseRunInfo) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

func init() {
	proto.RegisterEnum("thunder.RequestMsgid", RequestMsgid_name, RequestMsgid_value)
	proto.RegisterEnum("thunder.ResponseMsgid", ResponseMsgid_name, ResponseMsgid_value)
	proto.RegisterEnum("thunder.Errno", Errno_name, Errno_value)
}
