// Code generated by protoc-gen-gogo.
// source: phproxyd.proto
// DO NOT EDIT!

/*
Package badoo_phproxyd is a generated protocol buffer package.

It is generated from these files:
	phproxyd.proto

It has these top-level messages:
	TagStatT
	TagRrdT
	ResponseGeneric
	RequestPing
	RequestRrd
	RequestStats
	ResponsePing
	ResponseRrd
	ResponseStats
	RequestRun
	RequestSoftRun
	ResponseSoftRun
	RequestCheck
	RequestSoftCheck
	RequestFree
	RequestSoftFree
	ResponseCheck
	SoftCheckT
	ResponseSoftCheck
	RequestTerminate
*/
package badoo_phproxyd

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RequestMsgid int32

const (
	RequestMsgid_REQUEST_RRD        RequestMsgid = 1
	RequestMsgid_REQUEST_PING       RequestMsgid = 2
	RequestMsgid_REQUEST_STATS      RequestMsgid = 3
	RequestMsgid_REQUEST_RUN        RequestMsgid = 4
	RequestMsgid_REQUEST_CHECK      RequestMsgid = 5
	RequestMsgid_REQUEST_FREE       RequestMsgid = 6
	RequestMsgid_REQUEST_TERMINATE  RequestMsgid = 7
	RequestMsgid_REQUEST_SOFT_RUN   RequestMsgid = 8
	RequestMsgid_REQUEST_SOFT_CHECK RequestMsgid = 9
	RequestMsgid_REQUEST_SOFT_FREE  RequestMsgid = 10
)

var RequestMsgid_name = map[int32]string{
	1:  "REQUEST_RRD",
	2:  "REQUEST_PING",
	3:  "REQUEST_STATS",
	4:  "REQUEST_RUN",
	5:  "REQUEST_CHECK",
	6:  "REQUEST_FREE",
	7:  "REQUEST_TERMINATE",
	8:  "REQUEST_SOFT_RUN",
	9:  "REQUEST_SOFT_CHECK",
	10: "REQUEST_SOFT_FREE",
}
var RequestMsgid_value = map[string]int32{
	"REQUEST_RRD":        1,
	"REQUEST_PING":       2,
	"REQUEST_STATS":      3,
	"REQUEST_RUN":        4,
	"REQUEST_CHECK":      5,
	"REQUEST_FREE":       6,
	"REQUEST_TERMINATE":  7,
	"REQUEST_SOFT_RUN":   8,
	"REQUEST_SOFT_CHECK": 9,
	"REQUEST_SOFT_FREE":  10,
}

func (x RequestMsgid) Enum() *RequestMsgid {
	p := new(RequestMsgid)
	*p = x
	return p
}
func (x RequestMsgid) String() string {
	return proto.EnumName(RequestMsgid_name, int32(x))
}
func (x *RequestMsgid) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestMsgid_value, data, "RequestMsgid")
	if err != nil {
		return err
	}
	*x = RequestMsgid(value)
	return nil
}

type ResponseMsgid int32

const (
	ResponseMsgid_RESPONSE_GENERIC    ResponseMsgid = 1
	ResponseMsgid_RESPONSE_PING       ResponseMsgid = 2
	ResponseMsgid_RESPONSE_RRD        ResponseMsgid = 3
	ResponseMsgid_RESPONSE_STATS      ResponseMsgid = 4
	ResponseMsgid_RESPONSE_CHECK      ResponseMsgid = 5
	ResponseMsgid_RESPONSE_SOFT_CHECK ResponseMsgid = 6
	ResponseMsgid_RESPONSE_SOFT_RUN   ResponseMsgid = 7
)

var ResponseMsgid_name = map[int32]string{
	1: "RESPONSE_GENERIC",
	2: "RESPONSE_PING",
	3: "RESPONSE_RRD",
	4: "RESPONSE_STATS",
	5: "RESPONSE_CHECK",
	6: "RESPONSE_SOFT_CHECK",
	7: "RESPONSE_SOFT_RUN",
}
var ResponseMsgid_value = map[string]int32{
	"RESPONSE_GENERIC":    1,
	"RESPONSE_PING":       2,
	"RESPONSE_RRD":        3,
	"RESPONSE_STATS":      4,
	"RESPONSE_CHECK":      5,
	"RESPONSE_SOFT_CHECK": 6,
	"RESPONSE_SOFT_RUN":   7,
}

func (x ResponseMsgid) Enum() *ResponseMsgid {
	p := new(ResponseMsgid)
	*p = x
	return p
}
func (x ResponseMsgid) String() string {
	return proto.EnumName(ResponseMsgid_name, int32(x))
}
func (x *ResponseMsgid) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResponseMsgid_value, data, "ResponseMsgid")
	if err != nil {
		return err
	}
	*x = ResponseMsgid(value)
	return nil
}

type Errno int32

const (
	Errno_ERRNO_GENERIC            Errno = 1
	Errno_ERRNO_RUN_FAILED         Errno = 2
	Errno_ERRNO_ALREADY_RUNNING    Errno = 3
	Errno_ERRNO_NOT_FOUND          Errno = 4
	Errno_ERRNO_WORKING            Errno = 5
	Errno_ERRNO_NO_MEMORY          Errno = 6
	Errno_ERRNO_SUCCESS_FINISHED   Errno = 7
	Errno_ERRNO_FAILED_FINISHED    Errno = 8
	Errno_ERRNO_WAIT_FOR_FREE      Errno = 9
	Errno_ERRNO_START_CHILD_FAILED Errno = 10
)

var Errno_name = map[int32]string{
	1:  "ERRNO_GENERIC",
	2:  "ERRNO_RUN_FAILED",
	3:  "ERRNO_ALREADY_RUNNING",
	4:  "ERRNO_NOT_FOUND",
	5:  "ERRNO_WORKING",
	6:  "ERRNO_NO_MEMORY",
	7:  "ERRNO_SUCCESS_FINISHED",
	8:  "ERRNO_FAILED_FINISHED",
	9:  "ERRNO_WAIT_FOR_FREE",
	10: "ERRNO_START_CHILD_FAILED",
}
var Errno_value = map[string]int32{
	"ERRNO_GENERIC":            1,
	"ERRNO_RUN_FAILED":         2,
	"ERRNO_ALREADY_RUNNING":    3,
	"ERRNO_NOT_FOUND":          4,
	"ERRNO_WORKING":            5,
	"ERRNO_NO_MEMORY":          6,
	"ERRNO_SUCCESS_FINISHED":   7,
	"ERRNO_FAILED_FINISHED":    8,
	"ERRNO_WAIT_FOR_FREE":      9,
	"ERRNO_START_CHILD_FAILED": 10,
}

func (x Errno) Enum() *Errno {
	p := new(Errno)
	*p = x
	return p
}
func (x Errno) String() string {
	return proto.EnumName(Errno_name, int32(x))
}
func (x *Errno) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Errno_value, data, "Errno")
	if err != nil {
		return err
	}
	*x = Errno(value)
	return nil
}

type PhproxydStatusT int32

const (
	PhproxydStatusT_STATUS_OK     PhproxydStatusT = 1
	PhproxydStatusT_STATUS_FAILED PhproxydStatusT = 2
)

var PhproxydStatusT_name = map[int32]string{
	1: "STATUS_OK",
	2: "STATUS_FAILED",
}
var PhproxydStatusT_value = map[string]int32{
	"STATUS_OK":     1,
	"STATUS_FAILED": 2,
}

func (x PhproxydStatusT) Enum() *PhproxydStatusT {
	p := new(PhproxydStatusT)
	*p = x
	return p
}
func (x PhproxydStatusT) String() string {
	return proto.EnumName(PhproxydStatusT_name, int32(x))
}
func (x *PhproxydStatusT) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PhproxydStatusT_value, data, "PhproxydStatusT")
	if err != nil {
		return err
	}
	*x = PhproxydStatusT(value)
	return nil
}

type StoreT int32

const (
	StoreT_FILES  StoreT = 1
	StoreT_MEMORY StoreT = 2
)

var StoreT_name = map[int32]string{
	1: "FILES",
	2: "MEMORY",
}
var StoreT_value = map[string]int32{
	"FILES":  1,
	"MEMORY": 2,
}

func (x StoreT) Enum() *StoreT {
	p := new(StoreT)
	*p = x
	return p
}
func (x StoreT) String() string {
	return proto.EnumName(StoreT_name, int32(x))
}
func (x *StoreT) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StoreT_value, data, "StoreT")
	if err != nil {
		return err
	}
	*x = StoreT(value)
	return nil
}

type TagStatT struct {
	Tag              *string `protobuf:"bytes,1,req,name=tag" json:"tag,omitempty"`
	Success          *uint32 `protobuf:"varint,2,req,name=success" json:"success,omitempty"`
	Failed           *uint32 `protobuf:"varint,3,req,name=failed" json:"failed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TagStatT) Reset()         { *m = TagStatT{} }
func (m *TagStatT) String() string { return proto.CompactTextString(m) }
func (*TagStatT) ProtoMessage()    {}

func (m *TagStatT) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *TagStatT) GetSuccess() uint32 {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return 0
}

func (m *TagStatT) GetFailed() uint32 {
	if m != nil && m.Failed != nil {
		return *m.Failed
	}
	return 0
}

type TagRrdT struct {
	Tag              *string `protobuf:"bytes,1,req,name=tag" json:"tag,omitempty"`
	TmClean          *uint64 `protobuf:"varint,2,req,name=tm_clean" json:"tm_clean,omitempty"`
	Success          *uint32 `protobuf:"varint,3,req,name=success" json:"success,omitempty"`
	Failed           *uint32 `protobuf:"varint,4,req,name=failed" json:"failed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TagRrdT) Reset()         { *m = TagRrdT{} }
func (m *TagRrdT) String() string { return proto.CompactTextString(m) }
func (*TagRrdT) ProtoMessage()    {}

func (m *TagRrdT) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *TagRrdT) GetTmClean() uint64 {
	if m != nil && m.TmClean != nil {
		return *m.TmClean
	}
	return 0
}

func (m *TagRrdT) GetSuccess() uint32 {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return 0
}

func (m *TagRrdT) GetFailed() uint32 {
	if m != nil && m.Failed != nil {
		return *m.Failed
	}
	return 0
}

type ResponseGeneric struct {
	ErrorCode        *int32  `protobuf:"zigzag32,1,req,name=error_code" json:"error_code,omitempty"`
	ErrorText        *string `protobuf:"bytes,2,opt,name=error_text" json:"error_text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponseGeneric) Reset()         { *m = ResponseGeneric{} }
func (m *ResponseGeneric) String() string { return proto.CompactTextString(m) }
func (*ResponseGeneric) ProtoMessage()    {}

func (m *ResponseGeneric) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *ResponseGeneric) GetErrorText() string {
	if m != nil && m.ErrorText != nil {
		return *m.ErrorText
	}
	return ""
}

type RequestPing struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RequestPing) Reset()         { *m = RequestPing{} }
func (m *RequestPing) String() string { return proto.CompactTextString(m) }
func (*RequestPing) ProtoMessage()    {}

type RequestRrd struct {
	Tags             []string `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
	Clean            *uint32  `protobuf:"varint,2,req,name=clean" json:"clean,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RequestRrd) Reset()         { *m = RequestRrd{} }
func (m *RequestRrd) String() string { return proto.CompactTextString(m) }
func (*RequestRrd) ProtoMessage()    {}

func (m *RequestRrd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RequestRrd) GetClean() uint32 {
	if m != nil && m.Clean != nil {
		return *m.Clean
	}
	return 0
}

type RequestStats struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RequestStats) Reset()         { *m = RequestStats{} }
func (m *RequestStats) String() string { return proto.CompactTextString(m) }
func (*RequestStats) ProtoMessage()    {}

type ResponsePing struct {
	Status           *PhproxydStatusT `protobuf:"varint,1,req,name=status,enum=badoo.phproxyd.PhproxydStatusT" json:"status,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ResponsePing) Reset()         { *m = ResponsePing{} }
func (m *ResponsePing) String() string { return proto.CompactTextString(m) }
func (*ResponsePing) ProtoMessage()    {}

func (m *ResponsePing) GetStatus() PhproxydStatusT {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return PhproxydStatusT_STATUS_OK
}

type ResponseRrd struct {
	Vmsize            *string    `protobuf:"bytes,1,req,name=vmsize" json:"vmsize,omitempty"`
	UtimeTvSec        *uint64    `protobuf:"varint,2,req,name=utime_tv_sec" json:"utime_tv_sec,omitempty"`
	UtimeTvUsec       *uint64    `protobuf:"varint,3,req,name=utime_tv_usec" json:"utime_tv_usec,omitempty"`
	StimeTvSec        *uint64    `protobuf:"varint,4,req,name=stime_tv_sec" json:"stime_tv_sec,omitempty"`
	StimeTvUsec       *uint64    `protobuf:"varint,5,req,name=stime_tv_usec" json:"stime_tv_usec,omitempty"`
	CommandsCnt       *uint64    `protobuf:"varint,6,req,name=commands_cnt" json:"commands_cnt,omitempty"`
	FailedCommandsCnt *uint64    `protobuf:"varint,7,req,name=failed_commands_cnt" json:"failed_commands_cnt,omitempty"`
	Rrd               []*TagRrdT `protobuf:"bytes,8,rep,name=rrd" json:"rrd,omitempty"`
	XXX_unrecognized  []byte     `json:"-"`
}

func (m *ResponseRrd) Reset()         { *m = ResponseRrd{} }
func (m *ResponseRrd) String() string { return proto.CompactTextString(m) }
func (*ResponseRrd) ProtoMessage()    {}

func (m *ResponseRrd) GetVmsize() string {
	if m != nil && m.Vmsize != nil {
		return *m.Vmsize
	}
	return ""
}

func (m *ResponseRrd) GetUtimeTvSec() uint64 {
	if m != nil && m.UtimeTvSec != nil {
		return *m.UtimeTvSec
	}
	return 0
}

func (m *ResponseRrd) GetUtimeTvUsec() uint64 {
	if m != nil && m.UtimeTvUsec != nil {
		return *m.UtimeTvUsec
	}
	return 0
}

func (m *ResponseRrd) GetStimeTvSec() uint64 {
	if m != nil && m.StimeTvSec != nil {
		return *m.StimeTvSec
	}
	return 0
}

func (m *ResponseRrd) GetStimeTvUsec() uint64 {
	if m != nil && m.StimeTvUsec != nil {
		return *m.StimeTvUsec
	}
	return 0
}

func (m *ResponseRrd) GetCommandsCnt() uint64 {
	if m != nil && m.CommandsCnt != nil {
		return *m.CommandsCnt
	}
	return 0
}

func (m *ResponseRrd) GetFailedCommandsCnt() uint64 {
	if m != nil && m.FailedCommandsCnt != nil {
		return *m.FailedCommandsCnt
	}
	return 0
}

func (m *ResponseRrd) GetRrd() []*TagRrdT {
	if m != nil {
		return m.Rrd
	}
	return nil
}

type ResponseStats struct {
	Vmsize            *string     `protobuf:"bytes,1,req,name=vmsize" json:"vmsize,omitempty"`
	UtimeTvSec        *uint64     `protobuf:"varint,2,req,name=utime_tv_sec" json:"utime_tv_sec,omitempty"`
	UtimeTvUsec       *uint64     `protobuf:"varint,3,req,name=utime_tv_usec" json:"utime_tv_usec,omitempty"`
	StimeTvSec        *uint64     `protobuf:"varint,4,req,name=stime_tv_sec" json:"stime_tv_sec,omitempty"`
	StimeTvUsec       *uint64     `protobuf:"varint,5,req,name=stime_tv_usec" json:"stime_tv_usec,omitempty"`
	CommandsCnt       *uint64     `protobuf:"varint,6,req,name=commands_cnt" json:"commands_cnt,omitempty"`
	FailedCommandsCnt *uint64     `protobuf:"varint,7,req,name=failed_commands_cnt" json:"failed_commands_cnt,omitempty"`
	Stats             []*TagStatT `protobuf:"bytes,8,rep,name=stats" json:"stats,omitempty"`
	XXX_unrecognized  []byte      `json:"-"`
}

func (m *ResponseStats) Reset()         { *m = ResponseStats{} }
func (m *ResponseStats) String() string { return proto.CompactTextString(m) }
func (*ResponseStats) ProtoMessage()    {}

func (m *ResponseStats) GetVmsize() string {
	if m != nil && m.Vmsize != nil {
		return *m.Vmsize
	}
	return ""
}

func (m *ResponseStats) GetUtimeTvSec() uint64 {
	if m != nil && m.UtimeTvSec != nil {
		return *m.UtimeTvSec
	}
	return 0
}

func (m *ResponseStats) GetUtimeTvUsec() uint64 {
	if m != nil && m.UtimeTvUsec != nil {
		return *m.UtimeTvUsec
	}
	return 0
}

func (m *ResponseStats) GetStimeTvSec() uint64 {
	if m != nil && m.StimeTvSec != nil {
		return *m.StimeTvSec
	}
	return 0
}

func (m *ResponseStats) GetStimeTvUsec() uint64 {
	if m != nil && m.StimeTvUsec != nil {
		return *m.StimeTvUsec
	}
	return 0
}

func (m *ResponseStats) GetCommandsCnt() uint64 {
	if m != nil && m.CommandsCnt != nil {
		return *m.CommandsCnt
	}
	return 0
}

func (m *ResponseStats) GetFailedCommandsCnt() uint64 {
	if m != nil && m.FailedCommandsCnt != nil {
		return *m.FailedCommandsCnt
	}
	return 0
}

func (m *ResponseStats) GetStats() []*TagStatT {
	if m != nil {
		return m.Stats
	}
	return nil
}

type RequestRun struct {
	Script           *string  `protobuf:"bytes,1,req,name=script" json:"script,omitempty"`
	Hash             *uint64  `protobuf:"varint,2,req,name=hash" json:"hash,omitempty"`
	Tag              *string  `protobuf:"bytes,3,req,name=tag" json:"tag,omitempty"`
	Force            *int32   `protobuf:"zigzag32,4,opt,name=force" json:"force,omitempty"`
	Params           []string `protobuf:"bytes,5,rep,name=params" json:"params,omitempty"`
	Store            *StoreT  `protobuf:"varint,6,opt,name=store,enum=badoo.phproxyd.StoreT,def=2" json:"store,omitempty"`
	FreeAfterRun     *bool    `protobuf:"varint,7,opt,name=free_after_run,def=1" json:"free_after_run,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RequestRun) Reset()         { *m = RequestRun{} }
func (m *RequestRun) String() string { return proto.CompactTextString(m) }
func (*RequestRun) ProtoMessage()    {}

const Default_RequestRun_Store StoreT = StoreT_MEMORY
const Default_RequestRun_FreeAfterRun bool = true

func (m *RequestRun) GetScript() string {
	if m != nil && m.Script != nil {
		return *m.Script
	}
	return ""
}

func (m *RequestRun) GetHash() uint64 {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return 0
}

func (m *RequestRun) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *RequestRun) GetForce() int32 {
	if m != nil && m.Force != nil {
		return *m.Force
	}
	return 0
}

func (m *RequestRun) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *RequestRun) GetStore() StoreT {
	if m != nil && m.Store != nil {
		return *m.Store
	}
	return Default_RequestRun_Store
}

func (m *RequestRun) GetFreeAfterRun() bool {
	if m != nil && m.FreeAfterRun != nil {
		return *m.FreeAfterRun
	}
	return Default_RequestRun_FreeAfterRun
}

type RequestSoftRun struct {
	Script           *string `protobuf:"bytes,1,req,name=script" json:"script,omitempty"`
	Hash             *uint64 `protobuf:"varint,2,opt,name=hash" json:"hash,omitempty"`
	Data             *string `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestSoftRun) Reset()         { *m = RequestSoftRun{} }
func (m *RequestSoftRun) String() string { return proto.CompactTextString(m) }
func (*RequestSoftRun) ProtoMessage()    {}

func (m *RequestSoftRun) GetScript() string {
	if m != nil && m.Script != nil {
		return *m.Script
	}
	return ""
}

func (m *RequestSoftRun) GetHash() uint64 {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return 0
}

func (m *RequestSoftRun) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

type ResponseSoftRun struct {
	Hash             *uint64 `protobuf:"varint,1,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponseSoftRun) Reset()         { *m = ResponseSoftRun{} }
func (m *ResponseSoftRun) String() string { return proto.CompactTextString(m) }
func (*ResponseSoftRun) ProtoMessage()    {}

func (m *ResponseSoftRun) GetHash() uint64 {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return 0
}

type RequestCheck struct {
	Hash             *uint64 `protobuf:"varint,2,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestCheck) Reset()         { *m = RequestCheck{} }
func (m *RequestCheck) String() string { return proto.CompactTextString(m) }
func (*RequestCheck) ProtoMessage()    {}

func (m *RequestCheck) GetHash() uint64 {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return 0
}

type RequestSoftCheck struct {
	Hash             []uint64 `protobuf:"varint,1,rep,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RequestSoftCheck) Reset()         { *m = RequestSoftCheck{} }
func (m *RequestSoftCheck) String() string { return proto.CompactTextString(m) }
func (*RequestSoftCheck) ProtoMessage()    {}

func (m *RequestSoftCheck) GetHash() []uint64 {
	if m != nil {
		return m.Hash
	}
	return nil
}

type RequestFree struct {
	Hash             *uint64 `protobuf:"varint,2,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestFree) Reset()         { *m = RequestFree{} }
func (m *RequestFree) String() string { return proto.CompactTextString(m) }
func (*RequestFree) ProtoMessage()    {}

func (m *RequestFree) GetHash() uint64 {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return 0
}

type RequestSoftFree struct {
	Hash             []uint64 `protobuf:"varint,1,rep,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RequestSoftFree) Reset()         { *m = RequestSoftFree{} }
func (m *RequestSoftFree) String() string { return proto.CompactTextString(m) }
func (*RequestSoftFree) ProtoMessage()    {}

func (m *RequestSoftFree) GetHash() []uint64 {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ResponseCheck struct {
	ErrorCode        *int32  `protobuf:"zigzag32,1,req,name=error_code" json:"error_code,omitempty"`
	ErrorText        *string `protobuf:"bytes,2,opt,name=error_text" json:"error_text,omitempty"`
	Response         *string `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
	UtimeTvSec       *uint64 `protobuf:"varint,4,opt,name=utime_tv_sec" json:"utime_tv_sec,omitempty"`
	UtimeTvUsec      *uint64 `protobuf:"varint,5,opt,name=utime_tv_usec" json:"utime_tv_usec,omitempty"`
	StimeTvSec       *uint64 `protobuf:"varint,6,opt,name=stime_tv_sec" json:"stime_tv_sec,omitempty"`
	StimeTvUsec      *uint64 `protobuf:"varint,7,opt,name=stime_tv_usec" json:"stime_tv_usec,omitempty"`
	Retcode          *int32  `protobuf:"zigzag32,8,opt,name=retcode" json:"retcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponseCheck) Reset()         { *m = ResponseCheck{} }
func (m *ResponseCheck) String() string { return proto.CompactTextString(m) }
func (*ResponseCheck) ProtoMessage()    {}

func (m *ResponseCheck) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *ResponseCheck) GetErrorText() string {
	if m != nil && m.ErrorText != nil {
		return *m.ErrorText
	}
	return ""
}

func (m *ResponseCheck) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

func (m *ResponseCheck) GetUtimeTvSec() uint64 {
	if m != nil && m.UtimeTvSec != nil {
		return *m.UtimeTvSec
	}
	return 0
}

func (m *ResponseCheck) GetUtimeTvUsec() uint64 {
	if m != nil && m.UtimeTvUsec != nil {
		return *m.UtimeTvUsec
	}
	return 0
}

func (m *ResponseCheck) GetStimeTvSec() uint64 {
	if m != nil && m.StimeTvSec != nil {
		return *m.StimeTvSec
	}
	return 0
}

func (m *ResponseCheck) GetStimeTvUsec() uint64 {
	if m != nil && m.StimeTvUsec != nil {
		return *m.StimeTvUsec
	}
	return 0
}

func (m *ResponseCheck) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

type SoftCheckT struct {
	Hash             *uint64 `protobuf:"varint,1,req,name=hash" json:"hash,omitempty"`
	Response         *string `protobuf:"bytes,2,req,name=response" json:"response,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SoftCheckT) Reset()         { *m = SoftCheckT{} }
func (m *SoftCheckT) String() string { return proto.CompactTextString(m) }
func (*SoftCheckT) ProtoMessage()    {}

func (m *SoftCheckT) GetHash() uint64 {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return 0
}

func (m *SoftCheckT) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

type ResponseSoftCheck struct {
	Stats            []*SoftCheckT `protobuf:"bytes,1,rep,name=stats" json:"stats,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ResponseSoftCheck) Reset()         { *m = ResponseSoftCheck{} }
func (m *ResponseSoftCheck) String() string { return proto.CompactTextString(m) }
func (*ResponseSoftCheck) ProtoMessage()    {}

func (m *ResponseSoftCheck) GetStats() []*SoftCheckT {
	if m != nil {
		return m.Stats
	}
	return nil
}

type RequestTerminate struct {
	Hash             *uint64 `protobuf:"varint,1,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestTerminate) Reset()         { *m = RequestTerminate{} }
func (m *RequestTerminate) String() string { return proto.CompactTextString(m) }
func (*RequestTerminate) ProtoMessage()    {}

func (m *RequestTerminate) GetHash() uint64 {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return 0
}

func init() {
	proto.RegisterEnum("badoo.phproxyd.RequestMsgid", RequestMsgid_name, RequestMsgid_value)
	proto.RegisterEnum("badoo.phproxyd.ResponseMsgid", ResponseMsgid_name, ResponseMsgid_value)
	proto.RegisterEnum("badoo.phproxyd.Errno", Errno_name, Errno_value)
	proto.RegisterEnum("badoo.phproxyd.PhproxydStatusT", PhproxydStatusT_name, PhproxydStatusT_value)
	proto.RegisterEnum("badoo.phproxyd.StoreT", StoreT_name, StoreT_value)
}
